spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
mybatis:
  mapper-locations: classpath:mapper/*.xml